### PR TITLE
Fix `_is_reverse_scale`

### PR DESCRIPTION
**Pull request by nzw0301**
## Motivation

The current implementation of `optuna.visualization.plot_parallel_coordinate` raises an error as reported in https://github.com/optuna/optuna/issues/3423#issuecomment-1084602443. This bug has been introduced by https://github.com/optuna/optuna/pull/3376 (me!).

## Description of the changes

- Add tests to cover the case raising an error in https://github.com/optuna/optuna/issues/3423#issuecomment-1084602443
- Update the definition of `_is_reverse_scale`
- Fix typos

### CODE REVIEW

**Comment by himkt** [comment]
```
AttributeError: module 'distutils' has no attribute 'version'
[W 2022-03-31 14:58:39,334] Trial 0 failed because of the following error: ProcessExitedException('process 0 terminated with exit code 1')
[1:08](https://preferred.slack.com/archives/D0336TDTDL5/p1648742891050109)
```

https://github.com/optuna/optuna/runs/5773187838?check_suite_focus=true#step:7:13262

**Review by himkt — APPROVED** [review]
LGTM.

**Comment by himkt** [comment]
Hi @xadrianzetx, I'd like you to take a look if you afford. Please let me know if you're busy. 🙋‍♂️

**Comment by xadrianzetx** [comment]
Sure!

File: optuna/visualization/_utils.py [hunk 1]
```diff
@@ -142,7 +142,6 @@ def _target(t: FrozenTrial) -> float:
     return filtered_trials
 
 
-def _is_reverse_scale(
-    target: Optional[Callable[[FrozenTrial], float]], direction: StudyDirection
-) -> bool:
-    return target is not None or direction == StudyDirection.MINIMIZE
+def _is_reverse_scale(study: Study, target: Optional[Callable[[FrozenTrial], float]]) -> bool:
+
+    return target is not None or study.direction == StudyDirection.MINIMIZE
```
[the remark this answers is not in the document]
Comment (nzw0301) [reply optuna/visualization/_utils.py:147]: Yes, I think you are right. In addition, if users are unhappy with the hard-coded colourmap, they can change because retuned plots are editable. I suppose we can mention this behavior in `target` arguments of the plot functions in the documentation.

[the remark this answers is not in the document]
Comment (xadrianzetx) [reply optuna/visualization/_utils.py:147]: :+1:

**Review by xadrianzetx — APPROVED** [review]
LGTM!

**Comment by nzw0301** [comment]
Thank you for your reviews!
