### ISSUE TITLE
TensorFlow examples do not work with TensorFlow==2.0.0.

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna#565]
**Conditions**
- Optuna version: 0.16.0
- Python version: 3.7.2
- OS: macOS 10.13.6
- Machine Learning library to be optimized: TensorFlow 2.0.0

**Code to reproduce**

`examples/tensorflow_*` and `examples/pruning/tensorflow_*` do not work with TensorFlow==2.0.0.

```
$ python examples/tensorflow_estimator_simple.py

Traceback (most recent call last):
  File "examples/tensorflow_estimator_simple.py", line 137, in <module>
    tf.app.run()
AttributeError: module 'tensorflow' has no attribute 'app'
```

```
$ python examples/tensorflow_eager_simple.py
Traceback (most recent call last):
  File "examples/tensorflow_eager_simple.py", line 22, in <module>
    import tensorflow.contrib.eager as tfe
ModuleNotFoundError: No module named 'tensorflow.contrib'
```

Related PR #564.
