### PR TITLE
Fix: TensorFlow eager example with TensorFlow 2.X

### LINKED ISSUE #565: TensorFlow examples do not work with TensorFlow==2.0.0.
**Conditions**
- Optuna version: 0.16.0
- Python version: 3.7.2
- OS: macOS 10.13.6
- Machine Learning library to be optimized: TensorFlow 2.0.0

**Code to reproduce**

`examples/tensorflow_*` and `examples/pruning/tensorflow_*` do not work with TensorFlow==2.0.0.

```
$ python examples/tensorflow_estimator_simple.py

Traceback (most recent call last):
  File "examples/tensorflow_estimator_simple.py", line 137, in <module>
    tf.app.run()
AttributeError: module 'tensorflow' has no attribute 'app'
```

```
$ python examples/tensorflow_eager_simple.py
Traceback (most recent call last):
  File "examples/tensorflow_eager_simple.py", line 22, in <module>
    import tensorflow.contrib.eager as tfe
ModuleNotFoundError: No module named 'tensorflow.contrib'
```

Related PR #564.

### PR DESCRIPTION
**Pull request by nuka137**
This PR fixes #565 .

**Summary**

* Eager execution mode is default in TF 2.X. So, removed `tf.enable_eager_execution()` which is not supported in TF 2.X.
* The optimization APIs are changed in TF 2.X. New APIs are as follows.
  * `tf.optimizers.RMSprop`
  * `tf.optimizers.Adam`
  * `tf.optimizers.SGD`

### CODE REVIEW

**Comment by toshihikoyanase** [comment]
In addition, we can raise errors like [this example](https://github.com/optuna/optuna/blob/master/examples/chainer_simple.py#L31-L32) if users use tensorflow<2.0.0. 
I think such a change is optional, and we can work on it in a follow-up PR.

**Comment by nuka137** [comment]
@toshihikoyanase 

Thanks for your review!
I fixed the issues you mentioned.
Also, I added version checker at the top of `examples/tensorflow_eager_simple.py`.
Could you review again?

P.S.
I also noticed that there is a example which uses TensorFlow Estimator (`tensorflow_estimator_simple.py`).
I think APIs provided by TensorFlow Estimator is also changed in TF 2.0.
In my environment, `tensorflow_estimator_simple.py` also raises error because of API change.
I will tackle this problem as well ASAP.
Thanks.

File: examples/tensorflow_eager_simple.py [hunk 1]
```diff
@@ -20,15 +20,18 @@
 
 import tensorflow as tf
 from tensorflow.keras.datasets import mnist
+import pkg_resources
```
Comment (toshihikoyanase) [inline examples/tensorflow_eager_simple.py]: Please reorder the imports in alphabetical order.

https://circleci.com/gh/optuna/optuna/26154
```
flake8 .
./examples/tensorflow_eager_simple.py:23:1: H306: imports not in alphabetical order (tensorflow.keras.datasets.mnist, pkg_resources)
1     H306: imports not in alphabetical order (tensorflow.keras.datasets.mnist, pkg_resources)
```

File: examples/tensorflow_eager_simple.py [hunk 2]
```diff
@@ -51,7 +54,7 @@ def create_model(trial):
 def create_optimizer(trial):
     # We optimize the choice of optimizers as well as their parameters.
     kwargs = {}
-    optimizer_options = ['RMSPropOptimizer', 'AdamOptimizer', 'MomentumOptimizer']
+    optimizer_options = ['RMSprop', 'Adam', 'SGD']
     optimizer_selected = trial.suggest_categorical('optimizer', optimizer_options)
     if optimizer_selected == 'RMSPropOptimizer':
```
Comment (c-bata) [inline examples/tensorflow_eager_simple.py]: Hi @nuka137 ! I'm not familiar with tensorflow, but it looks these conditions to set optimizer's arguments should be updated like:

```python
if optimizer_selected == 'RMSProp':
    kwargs['learning_rate'] = trial.suggest_loguniform('rmsprop_learning_rate', 1e-5, 1e-1)
    ...
elif optimizer_selected == 'Adam':
    ...
elif optimizer_selected == 'SGD':
    ...
```

Comment (toshihikoyanase) [reply examples/tensorflow_eager_simple.py]: @c-bata 
Good catch! Thank you.

File: examples/tensorflow_eager_simple.py (hunk 1 above)
Comment (nuka137) [reply examples/tensorflow_eager_simple.py]: Thanks! I fixed it.

File: examples/tensorflow_eager_simple.py (hunk 2 above)
Comment (nuka137) [reply examples/tensorflow_eager_simple.py]: @c-bata 

Thanks! I forgot to fix these.

@toshihikoyanase 

I also fixed the parameter names for `suggest_loguniform`.
Could you check them, please?

**Comment by nuka137** [comment]
Also I fixed TensorFlow estimator's example.
The patch is now in [my repository](https://github.com/nuka137/optuna/commit/9be0c90f7acf886bdd5fc961d0fb4c4fe2325779).
Should this merge into this PR or create new PR?

**Comment by nuka137** [comment]
@toshihikoyanase 

Yes, I agree with you.
I'll create new PR for it after I fix your issue.

**Comment by toshihikoyanase** [comment]
@nuka137 Thank you for creating #868.
I'll merge this PR after #868 to avoid CI failure.

**Comment by hvy** [comment]
#868 is not merged but I noticed that we must also update https://github.com/optuna/optuna/blob/master/examples/pruning/tensorflow_estimator_integration.py. Let me take a look at it.
