### ISSUE TITLE
AttributeError: module 'optuna.trial' has no attribute 'TrialState'

### ISSUE THREAD

**Issue by Crissman** [optuna/optuna#1120]
Error message running https://github.com/optuna/optuna/blob/master/examples/pruning/simple.py
On Optuna 1.3

```Traceback (most recent call last):
  File "simple.py", line 52, in <module>
    pruned_trials = [t for t in study.trials if t.state == optuna.trial.TrialState.PRUNED]
  File "simple.py", line 52, in <listcomp>
    pruned_trials = [t for t in study.trials if t.state == optuna.trial.TrialState.PRUNED]
AttributeError: module 'optuna.trial' has no attribute 'TrialState'
```

Should be `optuna.structs.TrialState.PRUNED`?

**Comment by hvy** [comment]
It's expected. You're trying to run an example from the `master` with an older version of Optuna (v1.3.0). You can either get an older example that works with v1.3.0, or install the latest `master`. C.f. https://github.com/optuna/optuna/pull/1101/files#diff-c1a684f35f39bf0b0408bb88c6d5106c.

**Comment by Crissman** [comment]
Understood. Thanks!
