### PR TITLE
Use Python 3.7 in checks CI job

### PR DESCRIPTION
**Pull request by toshihikoyanase**
## Motivation

mypy failed after merging #3026 as follows:

https://github.com/optuna/optuna/runs/4877266490?check_suite_focus=true

## Description of the changes

Revert Python version of checks.

### CODE REVIEW

**Review by hvy — APPROVED** [review]
LGTM!

**Review by HideakiImamura — APPROVED** [review]
LGTM.

**Comment by toshihikoyanase** [comment]
[Note] mypy on Python 3.8 actually found new type errors, for example, as follows. I'm trying to resolve them in a follow-up PR.

```console
optuna/samplers/_tpe/parzen_estimator.py:195: error: Argument 1 has incompatible type "ndarray[Any, dtype[Any]]"; expected "float"
```
