### ISSUE TITLE
'MedianPruner' object has no attribute '_n_min_trials'

### ISSUE THREAD

**Issue by chrismaliszewski** [optuna/optuna#2732]
The same kind of issue as https://github.com/optuna/optuna/issues/2729 after updating to 2.8.0 with a study loaded from pickle that was created on 2.5.0.

Trace:
```Epoch 1/4
   6/1214 [..............................] - ETA: 5:32 - loss: -0.1459 - accuracy: 0.0100 - binary_crossentropy: 0.9002 - binary_accuracy: 0.4804 - cosine_similarity: 0.1459 - categorical_crossentropy: 5.7268WARNING:tensorflow:Callback method `on_train_batch_end` is slow compared to the batch time (batch time: 0.1194s vs `on_train_batch_end` time: 0.1305s). Check your callbacks.
1214/1214 [==============================] - 395s 293ms/step - loss: -0.7491 - accuracy: 0.2546 - binary_crossentropy: 1.3429 - binary_accuracy: 0.8657 - cosine_similarity: 0.7491 - categorical_crossentropy: 3.6063 - val_loss: -0.5604 - val_accuracy: 0.2891 - val_binary_crossentropy: 0.4177 - val_binary_accuracy: 0.8896 - val_cosine_similarity: 0.5604 - val_categorical_crossentropy: 4.8951
[W 2021-06-07 21:34:47,809] Trial 143 failed because of the following error: AttributeError("'MedianPruner' object has no attribute '_n_min_trials'")
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/optuna/_optimize.py", line 216, in _run_trial
    value_or_values = func(trial)
  File "<ipython-input-6-c2a95d8e8976>", line 181, in objective
    callbacks=callbacks,
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py", line 1229, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/callbacks.py", line 435, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/usr/local/lib/python3.7/dist-packages/optuna/integration/tfkeras.py", line 60, in on_epoch_end
    if self._trial.should_prune():
  File "/usr/local/lib/python3.7/dist-packages/optuna/trial/_trial.py", line 626, in should_prune
    return self.study.pruner.prune(self.study, trial)
  File "/usr/local/lib/python3.7/dist-packages/optuna/pruners/_percentile.py", line 207, in prune
    all_trials, direction, step, self._percentile, self._n_min_trials
AttributeError: 'MedianPruner' object has no attribute '_n_min_trials'
```
```/usr/local/lib/python3.7/dist-packages/optuna/study.py in optimize(self, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)
    408             callbacks=callbacks,
    409             gc_after_trial=gc_after_trial,
--> 410             show_progress_bar=show_progress_bar,
    411         )
    412 

/usr/local/lib/python3.7/dist-packages/optuna/_optimize.py in _optimize(study, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)
     73                 reseed_sampler_rng=False,
     74                 time_start=None,
---> 75                 progress_bar=progress_bar,
     76             )
     77         else:

/usr/local/lib/python3.7/dist-packages/optuna/_optimize.py in _optimize_sequential(study, func, n_trials, timeout, catch, callbacks, gc_after_trial, reseed_sampler_rng, time_start, progress_bar)
    160 
    161         try:
--> 162             trial = _run_trial(study, func, catch)
    163         except Exception:
    164             raise

/usr/local/lib/python3.7/dist-packages/optuna/_optimize.py in _run_trial(study, func, catch)
    265 
    266     if state == TrialState.FAIL and func_err is not None and not isinstance(func_err, catch):
--> 267         raise func_err
    268     return trial
    269 

/usr/local/lib/python3.7/dist-packages/optuna/_optimize.py in _run_trial(study, func, catch)
    214 
    215     try:
--> 216         value_or_values = func(trial)
    217     except exceptions.TrialPruned as e:
    218         # TODO(mamu): Handle multi-objective cases.

<ipython-input-6-c2a95d8e8976> in objective(trial)
    179         validation_data=(data[1][INPUT_FORMAT], data[1][OUTPUT_FORMAT]),
    180         # validation_steps=VALIDATION_STEPS,
--> 181         callbacks=callbacks,
    182     )
    183 

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1227           epoch_logs.update(val_logs)
   1228 
-> 1229         callbacks.on_epoch_end(epoch, epoch_logs)
   1230         training_logs = epoch_logs
   1231         if self.stop_training:

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/callbacks.py in on_epoch_end(self, epoch, logs)
    433     logs = self._process_logs(logs)
    434     for callback in self.callbacks:
--> 435       callback.on_epoch_end(epoch, logs)
    436 
    437   def on_train_batch_begin(self, batch, logs=None):

/usr/local/lib/python3.7/dist-packages/optuna/integration/tfkeras.py in on_epoch_end(self, epoch, logs)
     58 
     59         # Prune trial if needed
---> 60         if self._trial.should_prune():
     61             message = "Trial was pruned at epoch {}.".format(epoch)
     62             raise optuna.TrialPruned(message)

/usr/local/lib/python3.7/dist-packages/optuna/trial/_trial.py in should_prune(self)
    624 
    625         trial = self.study._storage.get_trial(self._trial_id)
--> 626         return self.study.pruner.prune(self.study, trial)
    627 
    628     def set_user_attr(self, key: str, value: Any) -> None:

/usr/local/lib/python3.7/dist-packages/optuna/pruners/_percentile.py in prune(self, study, trial)
    205 
    206         p = _get_percentile_intermediate_result_over_trials(
--> 207             all_trials, direction, step, self._percentile, self._n_min_trials
    208         )
    209         if math.isnan(p):

AttributeError: 'MedianPruner' object has no attribute '_n_min_trials'
```

Presumably, to solve the issue I'll need to instantiate MedianPruner after loading the study.

Please make the error message better that suggests where the problem is. Another possible solution was provided in the attached issue.

**Comment by Crissman** [comment]
Closing for same reason as #2729 .
