### PR TITLE
Fix OptunaSearchCV by adding the method that was implemented in sklearn

### LINKED ISSUE #825: OptunaSearchCV does not support `scikit-learn>=0.22.1`.
## Expected behavior

The `OptunaSearchCV` does not work with the latest scikit-learn (v0.22.1). This is due to the update of the internal interface in [this commit](https://github.com/scikit-learn/scikit-learn/commit/46001e7cfb163b73a83d5adf73fb454e8a3c64b6).  More concretely, it removed `sklearn.model_selection._validation._index_param_value` which is used in `OptunaSearchCV` and added `sklearn.utils.validation._check_fit_params` instead.

`OptunaSearchCV` uses some other internal interface of scikit-learn, and I think it would be better to stop using them to avoid similar issues.

## Environment

- Optuna version: 0.19.0
- Python version: 3.7.5
- OS : `Linux 75b723335ed2 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 GNU/Linux`
- scikit-learn versions: `scikit-learn==0.22.1`

## Reproducible examples

Setup
```bash
$ docker run -it --rm python:3.7 bash
$ pip install scikit-learn
$ pip install optuna
```

Reproducible code
```python
>>> import sklearn
>>> import optuna.integration.sklearn

# The following line raises import error even if sklearn has been installed.
>>> optuna.integration.sklearn._check_sklearn_availability()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/optuna/integration/sklearn.py", line 65, in _check_sklearn_availability
    raise ImportError(
ImportError: scikit-learn is not available. Please install scikit-learn to use this feature. scikit-learn can be installed by executing `$ pip install scikit-learn>=0.19.0`. For further information, please refer to the installation guide of scikit-learn. (The actual import error is as follows: cannot import name '_index_param_value' from 'sklearn.model_selection._validation' (/usr/local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py))

# The actual cause of the above error.
>>> from sklearn.model_selection._validation import _index_param_value
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name '_index_param_value' from 'sklearn.model_selection._validation' (/usr/local/lib/python3.7/site-packages/sklearn/model_selection/_validation.py)

```

### PR DESCRIPTION
**Pull request by himkt**
This PR aims to resolve #825.

Optuna doesn't work with `scikit-learn>=0.22.1` since
it removed the private method `_index_param_value`, which was used in Optuna.
This PR adds `_index_param_value` and makes optuna work with the latest scikit-learn.

### CODE REVIEW

File: optuna/integration/sklearn.py [hunk 1]
```diff
@@ -69,6 +68,22 @@ def _check_sklearn_availability():
...
+
+
+def _index_param_value(
+    X,  # type: TwoDimArrayLikeType
+    v,  # type: Any
+    indices  # type: OneDimArrayLikeType
+):
+    # type: (...) -> Union[OneDimArrayLikeType, TwoDimArrayLikeType]
+    if not _is_arraylike(v) or _num_samples(v) != _num_samples(X):
+        return v
```
Comment (himkt) [inline optuna/integration/sklearn.py]: https://github.com/scikit-learn/scikit-learn/commit/46001e7cfb163b73a83d5adf73fb454e8a3c64b6#diff-60033c11a662f460e1567effd5faa6f0L949
The original implementation cared for a sparse matrix.
Should we also follow?

File: optuna/integration/sklearn.py [hunk 2]
```diff
@@ -69,6 +68,22 @@ def _check_sklearn_availability():
         )
 
 
+def _is_arraylike(x):
+    # type: (Any) -> bool
+    return hasattr(x, '__len__')
```
Comment (himkt) [inline optuna/integration/sklearn.py]: https://github.com/scikit-learn/scikit-learn/blob/c2ede74db053d4821c51e1de53f9f8522562e9b5/sklearn/utils/validation.py#L131
Should we also check `__array__` and `shape`?

**Comment by hvy** [comment]
Thanks @himkt! Before jumping on to reviewing the changes, I noticed that this private function is not tested (not via unit testes, nor examples). Could you possibly add some units tests or parameterizations to `OptunaSearchCV.fit` to cover this code path?

**Comment by hvy** [comment]
I'm wondering if it's not simpler to instead of reimplementing the function cannot check which of `_index_param_value ` and `_check_fit_params` is available and use the one available.

**Comment by himkt** [comment]
Thank you for the quick reply.

> I'm wondering if it's not simpler to instead of reimplementing the function cannot check which of _index_param_value and _check_fit_params is available and use the one available.

I reimplemented `_index_param_value` since I thought I should avoid using an internal method, which was based on the original issue (https://github.com/optuna/optuna/issues/825#issue-545531563).
If I made some mistakes, sorry but please let me know the intention.

I made the change to use `_check_fit_params` instead of `_index_param_value` in 15e8c73.
Does this change meet your suggestion?

And I noticed OptunaSearchCV doesn't work when `sample_weight` is specified.
I think the cause of this problem is that `_partial_fit_and_score` divide a dataset into
train and test section.
Although `len(X)` should be the same to `len(sample_weight)` in  `partial_fit`, `len(X_train)` is smaller than `len(sample_weight)` since it is a subset of `X`.
(https://github.com/optuna/optuna/blob/master/optuna/integration/sklearn.py#L273-L280)

**Comment by himkt** [comment]
I added the parameterization for `fit_params` in cabdf69.
However, it is not tested on CI, I don't know the reason...

I attach the result of CI.

<details>

```
$ poetry run python -m pytest tests/integration_tests/test_sklearn.py                                                                                           ± [ ● ][optunacv]
============================================================================== test session starts ===============================================================================
platform darwin -- Python 3.7.6, pytest-5.3.4, py-1.8.1, pluggy-0.13.1
rootdir: /Users/makoto-hiramatsu/work/github.com/himkt/optuna
collected 4 items

tests/integration_tests/test_sklearn.py ..F.                                                                                                                               [100%]

==================================================================================== FAILURES ====================================================================================
_____________________________________________________________________ test_optuna_search[sample_weight-True] _____________________________________________________________________

enable_pruning = True, fit_params = 'sample_weight'

    @pytest.mark.parametrize('enable_pruning', [True, False])
    @pytest.mark.parametrize('fit_params', [None, 'sample_weight'])
    @pytest.mark.filterwarnings('ignore::UserWarning')
    def test_optuna_search(enable_pruning, fit_params):
        # type: (bool, Optional[Dict]) -> None

        X, y = make_blobs(n_samples=10)
        est = SGDClassifier(max_iter=5, tol=1e-03)
        param_dist = {'alpha': distributions.LogUniformDistribution(1e-04, 1e+03)}
        optuna_search = integration.OptunaSearchCV(
            est,
            param_dist,
            cv=3,
            enable_pruning=enable_pruning,
            error_score='raise',
            max_iter=5,
            random_state=0,
            return_train_score=True
        )

        with pytest.raises(NotFittedError):
            optuna_search._check_is_fitted()

        if fit_params == 'sample_weight':
            sample_weight = np.ones_like(y)
>           optuna_search.fit(X, y, sample_weight=sample_weight)

tests/integration_tests/test_sklearn.py:39:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
optuna/integration/sklearn.py:888: in fit
    timeout=self.timeout
optuna/study.py:302: in optimize
    gc_after_trial, None)
optuna/study.py:538: in _optimize_sequential
    self._run_trial_and_callbacks(func, catch, callbacks, gc_after_trial)
optuna/study.py:550: in _run_trial_and_callbacks
    trial = self._run_trial(func, catch, gc_after_trial)
optuna/study.py:569: in _run_trial
    result = func(trial)
optuna/integration/sklearn.py:179: in __call__
    scores = self._cross_validate_with_pruning(trial, estimator)
optuna/integration/sklearn.py:232: in _cross_validate_with_pruning
    partial_fit_params
optuna/integration/sklearn.py:289: in _partial_fit_and_score
    raise e
optuna/integration/sklearn.py:285: in _partial_fit_and_score
    estimator.partial_fit(X_train, y_train, **partial_fit_params)
.venv/lib/python3.7/site-packages/sklearn/linear_model/_stochastic_gradient.py:677: in partial_fit
    coef_init=None, intercept_init=None)
.venv/lib/python3.7/site-packages/sklearn/linear_model/_stochastic_gradient.py:487: in _partial_fit
    sample_weight = _check_sample_weight(sample_weight, X)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

sample_weight = array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
X = array([[-3.8062851 ,  4.79186607],
       [-7.7797901 , -5.10435052],
       [-2.54407737,  7.46508466],
       [-5.09572121, -6.26211768],
       [ 1.22582781, -3.23136765],
       [ 0.62168829,  0.65997347]])
dtype = [<class 'numpy.float64'>, <class 'numpy.float32'>]

    def _check_sample_weight(sample_weight, X, dtype=None):
        """Validate sample weights.

        Note that passing sample_weight=None will output an array of ones.
        Therefore, in some cases, you may want to protect the call with:
        if sample_weight is not None:
            sample_weight = _check_sample_weight(...)

        Parameters
        ----------
        sample_weight : {ndarray, Number or None}, shape (n_samples,)
           Input sample weights.

        X : nd-array, list or sparse matrix
            Input data.

        dtype: dtype
           dtype of the validated `sample_weight`.
           If None, and the input `sample_weight` is an array, the dtype of the
           input is preserved; otherwise an array with the default numpy dtype
           is be allocated.  If `dtype` is not one of `float32`, `float64`,
           `None`, the output will be of dtype `float64`.

        Returns
        -------
        sample_weight : ndarray, shape (n_samples,)
           Validated sample weight. It is guaranteed to be "C" contiguous.
        """
        n_samples = _num_samples(X)

        if dtype is not None and dtype not in [np.float32, np.float64]:
            dtype = np.float64

        if sample_weight is None or isinstance(sample_weight, numbers.Number):
            if sample_weight is None:
                sample_weight = np.ones(n_samples, dtype=dtype)
            else:
                sample_weight = np.full(n_samples, sample_weight,
                                        dtype=dtype)
        else:
            if dtype is None:
                dtype = [np.float64, np.float32]
            sample_weight = check_array(
                sample_weight, accept_sparse=False, ensure_2d=False, dtype=dtype,
                order="C"
            )
            if sample_weight.ndim != 1:
                raise ValueError("Sample weights must be 1D array or scalar")

            if sample_weight.shape != (n_samples,):
                raise ValueError("sample_weight.shape == {}, expected {}!"
>                                .format(sample_weight.shape, (n_samples,)))
E               ValueError: sample_weight.shape == (10,), expected (6,)!

.venv/lib/python3.7/site-packages/sklearn/utils/validation.py:1253: ValueError
------------------------------------------------------------------------------ Captured stderr call ------------------------------------------------------------------------------
[W 2020-01-31 22:24:30,037] Setting status of trial#0 as TrialState.FAIL because of the following error: ValueError('sample_weight.shape == (10,), expected (6,)!')
Traceback (most recent call last):
  File "/Users/makoto-hiramatsu/work/github.com/himkt/optuna/optuna/study.py", line 569, in _run_trial
    result = func(trial)
  File "/Users/makoto-hiramatsu/work/github.com/himkt/optuna/optuna/integration/sklearn.py", line 179, in __call__
    scores = self._cross_validate_with_pruning(trial, estimator)
  File "/Users/makoto-hiramatsu/work/github.com/himkt/optuna/optuna/integration/sklearn.py", line 232, in _cross_validate_with_pruning
    partial_fit_params
  File "/Users/makoto-hiramatsu/work/github.com/himkt/optuna/optuna/integration/sklearn.py", line 289, in _partial_fit_and_score
    raise e
  File "/Users/makoto-hiramatsu/work/github.com/himkt/optuna/optuna/integration/sklearn.py", line 285, in _partial_fit_and_score
    estimator.partial_fit(X_train, y_train, **partial_fit_params)
  File "/Users/makoto-hiramatsu/work/github.com/himkt/optuna/.venv/lib/python3.7/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 677, in partial_fit
    coef_init=None, intercept_init=None)
  File "/Users/makoto-hiramatsu/work/github.com/himkt/optuna/.venv/lib/python3.7/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 487, in _partial_fit
    sample_weight = _check_sample_weight(sample_weight, X)
  File "/Users/makoto-hiramatsu/work/github.com/himkt/optuna/.venv/lib/python3.7/site-packages/sklearn/utils/validation.py", line 1253, in _check_sample_weight
    .format(sample_weight.shape, (n_samples,)))
ValueError: sample_weight.shape == (10,), expected (6,)!
================================================================================ warnings summary ================================================================================
tests/integration_tests/test_sklearn.py::test_optuna_search[None-True]
  /Users/makoto-hiramatsu/work/github.com/himkt/optuna/.venv/lib/python3.7/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.metrics.scorer module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.metrics. Anything that cannot be imported from sklearn.metrics is now part of the private API.
    warnings.warn(message, FutureWarning)

tests/integration_tests/test_sklearn.py::test_optuna_search[None-True]
tests/integration_tests/test_sklearn.py::test_optuna_search[None-False]
tests/integration_tests/test_sklearn.py::test_optuna_search[sample_weight-True]
tests/integration_tests/test_sklearn.py::test_optuna_search[sample_weight-False]
  /Users/makoto-hiramatsu/work/github.com/himkt/optuna/.venv/lib/python3.7/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
    warnings.warn(msg, category=FutureWarning)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
```

</details>

File: tests/integration_tests/test_sklearn.py [hunk 3]
```diff
@@ -2,15 +2,20 @@
...
+import numpy as np
+
 
 @pytest.mark.parametrize('enable_pruning', [True, False])
+@pytest.mark.parametrize('fit_params', [None, 'sample_weight'])
 @pytest.mark.filterwarnings('ignore::UserWarning')
-def test_optuna_search(enable_pruning):
-    # type: (bool) -> None
+def test_optuna_search(enable_pruning, fit_params):
+    # type: (bool, Optional[Dict]) -> None
```
Comment (crcrpar) [inline tests/integration_tests/test_sklearn.py]: I think the type of `fit_params` is `Optional[str]`.

File: optuna/integration/sklearn.py [hunk 4]
```diff
@@ -56,6 +57,24 @@
 _logger = logging.get_logger(__name__)
 
 
+def check_fit_params(
+    X,  # type: TwoDimArrayLikeType
+    fit_params,  # type: Dict
+    indices  # type: OneDimArrayLikeType
+):
+    assert _available
```
Comment (crcrpar) [inline optuna/integration/sklearn.py]: This line is redundant as the availability check is done before this function is called. ref: https://github.com/optuna/optuna/blob/4a5466cf089791d49dfc99e836d80ced011ac75e/optuna/integration/sklearn.py#L698
```suggestion

```

File: optuna/integration/sklearn.py [hunk 5]
```diff
@@ -56,6 +57,24 @@
 _logger = logging.get_logger(__name__)
 
 
+def check_fit_params(
+    X,  # type: TwoDimArrayLikeType
+    fit_params,  # type: Dict
+    indices  # type: OneDimArrayLikeType
+):
```
Comment (crcrpar) [inline optuna/integration/sklearn.py]: Could you annotate the return type?
Also, I suppose this method should be private (prefixed with `_`) as most users will not use this.

File: tests/integration_tests/test_sklearn.py [hunk 6]
```diff
@@ -2,15 +2,19 @@
...
+from typing import Optional
 
 from optuna import distributions
 from optuna import integration
 
+import numpy as np
+
 
 @pytest.mark.parametrize('enable_pruning', [True, False])
+@pytest.mark.parametrize('fit_params', [None, 'sample_weight'])
```
Comment (crcrpar) [inline tests/integration_tests/test_sklearn.py]: This is rather my taste, not comment.
However, I would use empty string instead of `None` as it avoids the import of `Optional`.

**Comment by himkt** [comment]
Thank you so much @crcrpar for taking the time to check my code!
I revised my PR. (Although I know this PR still needs to be fixed or discussed.)

**Comment by hvy** [comment]
As for the version checking, that is basically what I meant. Thanks @crcrpar for filling out. My point was that this approach might be a simple one to address #825. However, I'm not sure this is the best solution. The whole `OptunaSearchCV` implementation should be refactored as soon as possible to not use these private functions.

@himkt would you like to tackle that as well? It believe that'd make sense as a follow-up to this PR.

File: tests/integration_tests/test_sklearn.py [hunk 7]
```diff
@@ -29,7 +32,12 @@ def test_optuna_search(enable_pruning):
     with pytest.raises(NotFittedError):
         optuna_search._check_is_fitted()
 
-    optuna_search.fit(X, y)
+    if fit_params == 'sample_weight':
+        sample_weight = np.ones_like(y)
+        optuna_search.fit(X, y, sample_weight=sample_weight)
```
Comment (hvy) [inline tests/integration_tests/test_sklearn.py]: `sample_weight` won't work (shape mismatch error, observed in CI) as we're doing a CV and the number of samples will vary. How about testing `fit_params` only when pruning is disabled as follows (when pruning is enabled `fit_params` will be passed to both `fit` and `partial_fit` it seems).

```python
@pytest.mark.parametrize('enable_pruning', [True, False])
@pytest.mark.parametrize('fit_params', ['', 'sample_weight'])
@pytest.mark.filterwarnings('ignore::UserWarning')
def test_optuna_search(enable_pruning, fit_params):
    # type: (bool, str) -> None

    X, y = make_blobs(n_samples=10, centers=3)
    est = SGDClassifier(max_iter=5, tol=1e-03, warm_start=True)
    ...
    optuna_search = integration.OptunaSearchCV(
        est,
        param_dist,
        cv=3,
        enable_pruning=enable_pruning,
        error_score='raise',
        max_iter=5,
        random_state=0,
        return_train_score=True
    )
    ....
    if fit_params == 'sample_weight' and not enable_pruning:
        # `SGDClassifier.fit`, not `SGDClassifier.partial_fit`.
        optuna_search.fit(X, y, coef_init=np.ones((3, 2), dtype=np.float64))
    else:
        optuna_search.fit(X, y)
    ...
```

File: optuna/integration/sklearn.py [hunk 8]
```diff
@@ -56,6 +57,25 @@
...
+    # type: (...) -> Dict
+
+    if _sklearn_version >= '0.22.1':
+        return validation._check_fit_params(X, fit_params, indices)
+    else:  # '_sklearn_version < 0.22.1'
+        return {
+            key: validation._index_param_value(
```
Comment (hvy) [inline optuna/integration/sklearn.py]: The symbol `_index_param_value` must be explicitly imported, i.e. `from sklearn.model_selection._validation import _index_param_value`. You could do a conditional import at the submodule scope at the top of this script.

**Comment by crcrpar** [comment]
> My point was that this approach might be a simple one to address #825. However, I'm not sure this is the best solution. The whole `OptunaSearchCV` implementation should be refactored as soon as possible to not use these private functions.

Agree. As we experienced, it's natural to assume that internal methods will be changed again. Therefore, we should implement the feature by ourselves, though I suppose we should do that in follow-up PRs.

**Comment by himkt** [comment]
@hvy

> would you like to tackle that as well? It believe that'd make sense as a follow-up to this PR.

Yes, I'd like to work on it after this PR. :eyes:

File: optuna/integration/sklearn.py (hunk 8 above)
Comment (himkt) [reply optuna/integration/sklearn.py]: 57e8e61 meets your intention?

File: tests/integration_tests/test_sklearn.py (hunk 7 above)
Comment (himkt) [reply tests/integration_tests/test_sklearn.py]: It makes sense, thanks.
I revised my PR to use `coef_init` in 282f883.

File: optuna/integration/sklearn.py [hunk 9]
```diff
@@ -29,14 +36,14 @@
...
     _available = False
 
-from optuna import distributions
-from optuna import exceptions
-from optuna import logging
+if _available:
+    if _sklearn_version >= '0.22.1':
+        from sklearn.utils.validation import _check_fit_params as _sklearn_check_fit_params  # NOQA
+    else:
+        from sklearn.utils.validation import _index_param_value as _sklearn_index_param_value  # NOQA
```
Comment (crcrpar) [inline optuna/integration/sklearn.py]: [question] In my understanding, two `# NOQA` are used to pass flake8 check of too long line. Is this correct?

Comment (himkt) [reply optuna/integration/sklearn.py]: You're right.

Comment (crcrpar) [reply optuna/integration/sklearn.py]: Thanks. Could you take a look at https://github.com/himkt/optuna/pull/1?

File: optuna/integration/sklearn.py [hunk 10]
```diff
@@ -29,14 +36,14 @@
...
+    if _sklearn_version >= '0.22.1':
+        from sklearn.utils.validation import _check_fit_params as _sklearn_check_fit_params
+    else:
+        from sklearn.utils.validation import _index_param_value as _sklearn_index_param_value
+
 from optuna import samplers  # NOQA
-from optuna import structs
-from optuna import study as study_module
 from optuna import trial as trial_module  # NOQA
-from optuna import type_checking
```
Comment (hvy) [inline optuna/integration/sklearn.py]: A minor but let's be consistent with placing `optuna` import after the Python standard library, i.e. keeping them where they were. You could add `  #NOQA` to these imports.

Comment (himkt) [reply optuna/integration/sklearn.py]: @hvy Sorry for breaking a consistency, fixed in 4023962.

**Comment by hvy** [comment]
A huge nit but let me modify the PR title a bit. We usually place backticks around "code" and the title with a punctuation.
